"""Phase-1 partial build: emits data/datasets.js with REAL letter M, schedule,
and MNIST samples but a null mnistModel.  Lets scene agents work against real
2D and forward-process data while the MNIST training job runs in the
background.  When training finishes, build_data.py overwrites this file with
the full version (mnistModel + reference trajectories filled in).
"""
from __future__ import annotations
import json
import os
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
ROOT = HERE.parent
DATA_OUT = ROOT / "data" / "datasets.js"

sys.path.insert(0, str(HERE))
from build_schedule import build_schedule, T          # noqa: E402
from build_letter_m import build_letter_m             # noqa: E402
from build_mnist_samples import build_mnist_samples   # noqa: E402


def f32_str(x: float) -> str:
    f = float(np.float32(x))
    if f == 0.0:
        return "0"
    return f"{f:.7g}"


def f64_str(x: float) -> str:
    f = float(x)
    if f == 0.0:
        return "0"
    return f"{f:.10g}"


def main() -> None:
    sched = build_schedule()
    print(f"[1/3] schedule: T={sched['T']}")
    letter = build_letter_m()
    letter.pop("_perp_dists", None)
    print(f"[2/3] letter M: {len(letter['points'])} points")
    samples = build_mnist_samples()
    for s in samples:
        s.pop("_index", None)
    print(f"[3/3] MNIST samples: {len(samples)}")

    parts = [
        "/* Auto-generated by precompute/build_partial.py.\n"
        " * Phase-1 partial: real letter M + schedule + MNIST samples; mnistModel = null.\n"
        " * Replaced by precompute/build_data.py once MNIST training completes. */\n",
        "window.DATA = {\n",
        "  partial: true,\n",
        f"  T: {sched['T']},\n",
        "  betas: [" + ",".join(f64_str(b) for b in sched["betas"]) + "],\n",
        "  alphas: [" + ",".join(f64_str(a) for a in sched["alphas"]) + "],\n",
        "  alphaBars: [" + ",".join(f64_str(a) for a in sched["alphaBars"]) + "],\n",
    ]
    pts_strs = ["[" + f64_str(x) + "," + f64_str(y) + "]" for x, y in letter["points"]]
    parts.append("  letterM: {\n")
    parts.append("    points: [" + ",".join(pts_strs) + "],\n")
    bb = letter["bbox"]
    parts.append(
        "    bbox: {"
        f"xMin:{f64_str(bb['xMin'])},xMax:{f64_str(bb['xMax'])},"
        f"yMin:{f64_str(bb['yMin'])},yMax:{f64_str(bb['yMax'])}"
        "}\n  },\n"
    )

    parts.append("  mnistSamples: [\n")
    for s in samples:
        pix = ",".join(f32_str(p) for p in s["pixels"])
        parts.append(f"    {{label: {s['label']}, pixels: [{pix}]}},\n")
    parts.append("  ],\n")

    parts.append("  mnistModel: null,\n")
    parts.append("  mnistReferenceTrajectories: []\n")
    parts.append("};\n")

    DATA_OUT.parent.mkdir(parents=True, exist_ok=True)
    DATA_OUT.write_text("".join(parts))
    size_kb = DATA_OUT.stat().st_size / 1024
    print(f"\nwrote {DATA_OUT}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
